return {
    {
        -- [obsidian.nvim](https://github.com/epwalsh/obsidian.nvim)
        -- Obsidian like note-taking plugin for Neovim
        -----------------------------------------------------------------------
        'epwalsh/obsidian.nvim',
        -- opts = {
        --         dir = "~/Knowledge",
        --         log_level = vim.log.levels.DEBUG,
        --         daily_notes = {
        --                 folder = "journal",
        --                 date_format = "%Y-%m-%d %A",
        --                 alias_format = "%Y-%m-%d",
        --         },
        --         completion = {
        --                 nvim_cmp = true,
        --                 min_chars = 2,
        --                 new_notes_location = "current_dir",
        --                 prepend_note_id = false,
        --         },
        --         mappings = {
        --         },
        --         note_id_func = function(title)
        --                 return title
        --         end,
        --         disable_frontmatter = true,
        --         note_frontmatter_func = function(note)
        --                 local out = { id = note.id, aliases = note.aliases, tags = note.tags }
        --                 if note.metadata ~= nil and require("obsidian").util.table_length(note.metadata) > 0 then
        --                         for k, v in pairs(note.metadata) do
        --                                 out[k] = v
        --                         end
        --                 end
        --                 return out
        --         end,
        --         templates = {
        --                 subdir = "Resource/Template",
        --                 date_format = "%Y-%m-%d %A",
        --                 time_format = "%H:%M",
        --         },
        --         backlinks = {
        --                 height = 10,
        --                 wrap = true,
        --         },
        --         follow_url_func = function(url)
        --                 url = vim.fn.shellescape(url)
        --                 vim.fn.jobstart({ "open", url })
        --         end,
        --         use_advanced_uri = true,
        --         open_app_foreground = false,
        --         finder = "telescope.nvim",
        --         open_notes_in = "current"
        -- }
    },
}
